// <auto-generated />
using LDD_BT_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LDD_BT_MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421125256_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LDD_BT_MVC.Models.DangKyLopModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LopId")
                        .HasColumnType("int");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LopId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("LDD_BT_MVC.Models.GiaoVienModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("LDD_BT_MVC.Models.KhoaHocModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("LDD_BT_MVC.Models.LopModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GiaoVienId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("LDD_BT_MVC.Models.SinhVienModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("LDD_BT_MVC.Models.DangKyLopModel", b =>
                {
                    b.HasOne("LDD_BT_MVC.Models.LopModel", "Lop")
                        .WithMany("DangKyLops")
                        .HasForeignKey("LopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LDD_BT_MVC.Models.SinhVienModel", "SinhVien")
                        .WithMany("DangKyLops")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("LDD_BT_MVC.Models.LopModel", b =>
                {
                    b.HasOne("LDD_BT_MVC.Models.GiaoVienModel", "GiaoVien")
                        .WithMany("Lops")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LDD_BT_MVC.Models.KhoaHocModel", "KhoaHoc")
                        .WithMany("Lops")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("LDD_BT_MVC.Models.GiaoVienModel", b =>
                {
                    b.Navigation("Lops");
                });

            modelBuilder.Entity("LDD_BT_MVC.Models.KhoaHocModel", b =>
                {
                    b.Navigation("Lops");
                });

            modelBuilder.Entity("LDD_BT_MVC.Models.LopModel", b =>
                {
                    b.Navigation("DangKyLops");
                });

            modelBuilder.Entity("LDD_BT_MVC.Models.SinhVienModel", b =>
                {
                    b.Navigation("DangKyLops");
                });
#pragma warning restore 612, 618
        }
    }
}
